### PR TITLE
add an original literature

### PR DESCRIPTION
**Pull request by LovelyBuggies**

### CODE REVIEW

**Comment by emstoudenmire** [comment]
Thanks! Good idea to add this. Could you please update the Notes section, though, to reflect a description of this article? (Currenty it is reusing the same notes as for the Tensor Train paper.)

**Comment by LovelyBuggies** [comment]
@emstoudenmire Sorry for forgetting to replace the notes, LGTM now.

**Comment by emstoudenmire** [comment]
Thanks. I noticed also that the URL is still pointing to the Tensor Train article and not the Kolda article. Could you please update that as well?

**Comment by emstoudenmire** [comment]
Perfect thanks!

**Pull request merged**
